Fix broken link to installation documentation
khanhas/spicetify-cli pull request #1428
Opened 2022-01-25 16:26 UTC by Jakob-Ruf

Link to installation on website was broken (probably due to splitting it up into simple and advanced installation). Added a link for both simple and advanced installation

2022-01-25 17:53 UTC, afonsojramos requested changes
Thanks for the PR, completely forgot about this!

2022-01-25 17:53 UTC, afonsojramos commented on README.md
> +#### [Advanced Installation](https://spicetify.app/docs/getting-started/advanced-installation)
I'd rather just have a referral to the `simple-installation` actually. Can you remove the advanced installation link?

2022-01-25 18:05 UTC, Jakob-Ruf commented
Removed advanced link, please review again

2022-01-26 00:47 UTC, afonsojramos approved these changes

2022-01-26 00:47 UTC, merged