Add configurable blur size to popup lyrics
khanhas/spicetify-cli pull request #955
Opened 2021-08-06 18:57 UTC by ZT2wo

More options, why not

2021-08-07 17:39 UTC, TalEdd commented on Extensions/popupLyrics.js
> +    // Offload setInterval to a Worker to consistenly call tick function.
Wrong spelling

2021-08-07 17:39 UTC, TalEdd commented on Extensions/popupLyrics.js
> +    // Offload setInterval to a Worker to consistenly call tick function.
Should be consistently

2021-08-09 05:33 UTC, saxobroko requested changes

2021-08-09 05:33 UTC, saxobroko commented on Extensions/popupLyrics.js
> +    // Offload setInterval to a Worker to consistenly call tick function.
'consistenly' should be 'consistently'

2021-09-03 18:13 UTC, afonsojramos commented
Merged locally due to big conflicts.

2021-09-03 18:13 UTC, closed without merging